app:
  main:
    stackoverflow:
      key: fake-so-key
      access-token: fake-so-token
      token-disabled: true
    update-cron: "0 0 */12 * * ?"
  clients:
    bot-url: http://localhost:8080/bot/api
    github-token: fake-gh-key
    stack-overflow-url: stack
    github-url: github
  data:
    type: sql
  links-pagesize: 1

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Scrapper
  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver

server:
  port: 8008

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  config:
    classpath:log4j2.xml
