app:
  main:
    stackoverflow:
      key: ${SO_TOKEN_KEY}
      access-token: ${SO_ACCESS_TOKEN}
      token-disabled: true
    update-cron: "0 0 */12 * * ?"
  clients:
    bot-url: http://localhost:8080/bot/api
    github-token: ${GITHUB_TOKEN}
    stack-overflow-url: https://api.stackexchange.com/2.3
    github-url: https://api.github.com
    client-type: kafka
    timeout: 3000
    retry:
      max-attempts: 2
      wait-duration: 100
  data:
    type: sql
    redis: ${REDIS_URL}
    redis-ex-ms: 600000
    links-pagesize: 30

resilience2:
  retry:
    max-attempts: 4
    wait-duration: 100
    blacklisted-status-codes:
      - 400
      - 401
      - 403
      - 404
      - 405


spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
    change-log: classpath:/migrations/master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    kafka-topics:
      link-updates:
        name: link-updates
        partitions: 3

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  config:
    classpath:log4j2.xml
