app:
  telegram-token: ${TELEGRAM_TOKEN}
  help-message: "
            /start - Начать работу с ботом\n
            /help- Список команд\n
            /track - Начать отслеживание ссылки\n
            /untrack - Остановить отслеживание ссылки\n
            /list - Список отслеживаемых ссылок\n"
  scrapper-url: http://localhost:8081/scrapper/api

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  structured:
    format:
      console: ecs
