app:
  bot:
    settings:
      commands:
        - command: /start
          description: Начать работу с ботом
        - command: /help
          description: Список команд
        - command: /track
          description: Начать отслеживание ссылки
        - command: /untrack
          description: Остановить отслеживание ссылки
        - command: /list
          description: Список отслеживаемых ссылок
  telegram:
    telegram-token: ${TELEGRAM_TOKEN}
  clients:
    scrapper-url: http://localhost:8081/scrapper/api


spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

#logging:
#  structured:
#    format:
#      console: ecs
