app:
  bot:
    settings:
      commands:
        - command: /start
          description: Начать работу с ботом
        - command: /help
          description: Список команд
        - command: /track
          description: Начать отслеживание ссылки
        - command: /untrack
          description: Остановить отслеживание ссылки
        - command: /list
          description: Список отслеживаемых ссылок
  telegram:
    telegram-token: ${TELEGRAM_TOKEN}
  clients:
    scrapper-url: http://localhost:8081/scrapper/api


spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: localhost:29092
    dlq: link-updates-dlt
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

    kafka-topics-names:
      link-updates: link-updates

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  config:
    classpath:log4j2.xml
